language: cpp
compiler:
- clang
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - portaudio19-dev
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
branches:
  only:
    - master
    - dev
script:
  - mkdir build && cd build && cmake .. && make
