language: cpp
compiler:
- clang
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - portaudio19-dev
branches:
  only:
    - master
    - dev
script:
  - mkdir build && cd build && cmake .. && make
